name: Markdown Code Block Auto Lang
description: Automatically sets a language for Markdown code blocks in PR/issue descriptions if missing.

inputs:
  github-token:
    description: |
      GitHub token.
      The default one will work only for those who have access to the API.
      For public projects you'll need to create a fine-grained
      personal access token. Check README for step-by-step guide.
    required: true
    default: ${{ github.token }}

  language:
    description: Language to set for code blocks without specified language
    required: true

  silent:
    description: If true, no comments will be added to the PR/issue
    required: false
    default: 'false'

  what-to-update:
    description: |
      Which event types to update. Options: pull_request, issue, all (default: all).
      Accepts a single value or a multiline list.
    required: false
    default: |
      all

outputs:
  fixes:
    description: Number of code blocks that were fixed

runs:
  using: node20
  main: dist/index.js

branding:
  icon: code
  color: blue
